### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by jayx11** [TCDG/Scammer-Bingo-Reborn-Python#1]
![errorbingo](https://cloud.githubusercontent.com/assets/15267288/20659384/1fa407fe-b4f8-11e6-9701-32b72368f421.png)

i cant exactly run bat files on my arch machine so is there any other way to build it?

the requirements say _**any**_  OS with pygubu which i have installed and runs fine, however this gives me the above error. 

![errorbingo2](https://cloud.githubusercontent.com/assets/15267288/20659514/e20b009a-b4f8-11e6-8e0d-11130f11f1a4.png)

i tried running the bat file and there was a typo on "python" which i fixed but gave me the same error as you can see above. im really puzzled and kinda wanna learn python just so i can fix this myself

**Comment by Lyxnx** [comment]
- That file is a batch file, made for Windows
- Run `python main.py` manually from a terminal

**Comment by jayx11** [comment]
- I know it is a batch file for windows. i just stated there was a typo on  it
- I did run that, the first screencap shows the output

**Comment by mooncos** [comment]
It seems that there's a problem when the app tries to fetch the icon, this might be because of a different filesystem from the one this app was developed on. Will remove the icon feature until next update.

NB: Pythonw is not a typo, is a way to tell Windows to force the display into windowed mode

**Comment by mooncos** [comment]
Ok, I'm reopening it so that you can report about the new fix @jayx11

**Comment by mooncos** [comment]
Env issue was punctual, closing
